version: "3.7"

services:
  mongodb:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    networks:
      network_public:
        aliases:
          - mongodb   # agora “mongodb” será resolvido como tiledesk_mongodb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == workerserver02

  redis:
    image: redis:6.2
    networks:
      network_public:
        aliases:
          - redis
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == workerserver02

  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      network_public:
        aliases:
          - rabbitmq
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == workerserver02

  tiledesk:
    image: jonesdockerhub/docker_jones:2.10.82
    command: ["sh", "-c", "until nc -z mongodb 27017; do echo Waiting for mongodb; sleep 2; done; npm start"]
    environment:
      PORT: "3000"
      LOG_LEVEL: "debug"
      GLOBAL_SECRET: "nodeauthsecret"
      ADMIN_EMAIL: "admin@duobro.com.br"
      ADMIN_PASSWORD: "S3nh@F0rte!"
      SUPER_PASSWORD: "nodeauthsecret"
      CREATE_INITIAL_DATA: "true"
      MONGODB_URI: "mongodb://mongodb:27017/tiledesk"
      MONGODB_LOGS_URI: "mongodb://mongodb:27017/tiledesk-logs"
      EMAIL_ENABLED: "false"
      REDIS_URL: "redis://redis:6379"
      AMQP_URI: "amqp://guest:guest@rabbitmq:5672"
      EXTERNAL_BASE_URL: "https://inbox.duobro.com.br"
      EXTERNAL_MQTT_BASE_URL: "wss://inbox.duobro.com.br"
      GPTKEY: "${GPTKEY}"
      CHAT21_ENABLED: "false"
      CHAT21_ENGINE: "mqtt"
      CHAT21_URL: "http://localhost:8004"
      # CHAT21_MQTT_URL: "mqtt://tiledesk_mqtt:1883"
      # CHAT21_MQTT_PORT: "1883"
      # CHAT21_MQTT_USERNAME: "guest"
      # CHAT21_MQTT_PASSWORD: "guest"
      # CHAT21_MQTT_CLIENT_ID: "tiledesk_mqtt_client"
      # CHAT21_MQTT_TOPIC: "tiledesk_mqtt_topic"
 
    networks:
      - network_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == workerserver02
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tiledesk.rule=Host(`inbox.duobro.com.br`)"
        - "traefik.http.routers.tiledesk.entrypoints=websecure"
        - "traefik.http.routers.tiledesk.tls=true"
        - "traefik.http.routers.tiledesk.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.tiledesk.tls.domains[0].main=inbox.duobro.com.br"
        - "traefik.http.services.tiledesk.loadbalancer.server.port=3000"
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

volumes:
  mongo-data:

networks:
  network_public:
    external: true
    name: network_public
